module.exports = [
    '@tools',
    '@outdoorGear',
    '@electronics',
    '@partyEquipment',
    '@recreationVehicles',
    '@clothing',
    '@homeKitchen',
    '@toysGames',
    '@lawnGarden',
    '@sporting',
    '@businessEquipment',
    '@venues',
    '@localExperts',
    '@experiences',
    '@misc',
]